// <auto-generated />
using System;
using ComandesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComandesAPI.Migrations
{
    [DbContext(typeof(ComandesDbContext))]
    [Migration("20251210072649_PermitDeleteUserWithOrders")]
    partial class PermitDeleteUserWithOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ComandesAPI.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actiu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataCreacio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataModificacio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Estoc")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Preu")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_Articles_Categoria");

                    b.HasIndex("Nom")
                        .HasDatabaseName("IX_Articles_Nom");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actiu = false,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Ordinador portàtil per oficina amb pantalla de 15.6 polzades",
                            Estoc = 0,
                            Nom = "Ordinador portàtil",
                            Preu = 899.99m
                        },
                        new
                        {
                            Id = 2,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Ratolí òptic sense fils amb sensor de precisió",
                            Estoc = 50,
                            Nom = "Ratolí sense fils",
                            Preu = 25.50m
                        },
                        new
                        {
                            Id = 3,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Teclat mecànic retroil·luminat amb switches Cherry MX",
                            Estoc = 25,
                            Nom = "Teclat mecànic",
                            Preu = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Monitor LED Full HD 1920x1080 amb connexió HDMI",
                            Estoc = 15,
                            Nom = "Monitor 24 polzades",
                            Preu = 189.99m
                        },
                        new
                        {
                            Id = 5,
                            Actiu = false,
                            Categoria = "Mobiliari",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Cadira ergonòmica amb suport lumbar ajustable",
                            Estoc = 8,
                            Nom = "Cadira d'oficina",
                            Preu = 149.99m
                        },
                        new
                        {
                            Id = 6,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Impressora làser monocrom amb connexió Wi-Fi",
                            Estoc = 12,
                            Nom = "Impressora làser",
                            Preu = 89.99m
                        },
                        new
                        {
                            Id = 7,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Disc dur extern USB 3.0 de 1TB per còpies de seguretat",
                            Estoc = 30,
                            Nom = "Disc dur extern 1TB",
                            Preu = 59.99m
                        },
                        new
                        {
                            Id = 8,
                            Actiu = true,
                            Categoria = "Mobiliari",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Taula d'oficina de fusta amb calaixos i organitzador",
                            Estoc = 5,
                            Nom = "Taula d'oficina",
                            Preu = 299.99m
                        },
                        new
                        {
                            Id = 9,
                            Actiu = false,
                            Categoria = "Àudio",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Auriculars inalàmbrics amb cancel·lació de soroll",
                            Estoc = 20,
                            Nom = "Auriculars Bluetooth",
                            Preu = 79.99m
                        },
                        new
                        {
                            Id = 10,
                            Actiu = false,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Càmera web Full HD 1080p amb micròfon integrat",
                            Estoc = 18,
                            Nom = "Webcam HD",
                            Preu = 45.99m
                        });
                });

            modelBuilder.Entity("ComandesAPI.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actiu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAprovacio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCreacio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFinalitzacio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataModificacio")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DescomptePercentatge")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Estat")
                        .HasColumnType("int");

                    b.Property<decimal>("ImportDescompte")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroComanda")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observacions")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmbDescompte")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UsuariId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataCreacio")
                        .HasDatabaseName("IX_Comandes_DataCreacio");

                    b.HasIndex("Estat")
                        .HasDatabaseName("IX_Comandes_Estat");

                    b.HasIndex("NumeroComanda")
                        .IsUnique()
                        .HasDatabaseName("IX_Comandes_NumeroComanda");

                    b.HasIndex("UsuariId")
                        .HasDatabaseName("IX_Comandes_UsuariId");

                    b.ToTable("Comandes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actiu = true,
                            DataCreacio = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Estat = 0,
                            ImportDescompte = 0m,
                            NumeroComanda = "COM-2025-000001",
                            Observacions = "Primera comanda en fase d'elaboració",
                            Total = 370.48m,
                            TotalAmbDescompte = 370.48m,
                            UsuariId = 2
                        },
                        new
                        {
                            Id = 2,
                            Actiu = true,
                            DataCreacio = new DateTime(2025, 2, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 5m,
                            Estat = 1,
                            ImportDescompte = 47.00m,
                            NumeroComanda = "COM-2025-000002",
                            Observacions = "Material per nova oficina - urgent",
                            Total = 939.96m,
                            TotalAmbDescompte = 892.96m,
                            UsuariId = 2
                        },
                        new
                        {
                            Id = 3,
                            Actiu = true,
                            DataAprovacio = new DateTime(2025, 2, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            DataCreacio = new DateTime(2025, 2, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 10m,
                            Estat = 2,
                            ImportDescompte = 90.00m,
                            NumeroComanda = "COM-2025-000003",
                            Observacions = "Mobiliari per sala de reunions",
                            Total = 899.95m,
                            TotalAmbDescompte = 809.95m,
                            UsuariId = 2
                        },
                        new
                        {
                            Id = 4,
                            Actiu = true,
                            DataAprovacio = new DateTime(2025, 2, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            DataCreacio = new DateTime(2025, 2, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Estat = 3,
                            ImportDescompte = 0m,
                            NumeroComanda = "COM-2025-000004",
                            Observacions = "Equipament informàtic complet per 3 treballadors",
                            Total = 625.93m,
                            TotalAmbDescompte = 625.93m,
                            UsuariId = 2
                        },
                        new
                        {
                            Id = 5,
                            Actiu = true,
                            DataAprovacio = new DateTime(2025, 2, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            DataCreacio = new DateTime(2025, 2, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            DataFinalitzacio = new DateTime(2025, 2, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 5m,
                            Estat = 5,
                            ImportDescompte = 55.00m,
                            NumeroComanda = "COM-2025-000005",
                            Observacions = "Comanda completada i lliurada. Client satisfet.",
                            Total = 1099.94m,
                            TotalAmbDescompte = 1044.94m,
                            UsuariId = 2
                        });
                });

            modelBuilder.Entity("ComandesAPI.Models.LiniaComanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("ComandaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCreacio")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DescomptePercentatge")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Descripcio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("ImportDescompte")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NomProducte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<decimal>("PreuUnitari")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Quantitat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("IX_LiniesComanda_ArticleId");

                    b.HasIndex("ComandaId")
                        .HasDatabaseName("IX_LiniesComanda_ComandaId");

                    b.ToTable("LiniesComanda");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 2,
                            ComandaId = 1,
                            DataCreacio = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Ratolí òptic sense fils amb sensor de precisió",
                            ImportDescompte = 0m,
                            NomProducte = "Ratolí sense fils",
                            Ordre = 0,
                            PreuUnitari = 25.50m,
                            Quantitat = 5m,
                            Subtotal = 127.50m,
                            Total = 127.50m
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 10,
                            ComandaId = 1,
                            DataCreacio = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Càmera web Full HD 1080p amb micròfon integrat",
                            ImportDescompte = 0m,
                            NomProducte = "Webcam HD",
                            Ordre = 1,
                            PreuUnitari = 45.99m,
                            Quantitat = 3m,
                            Subtotal = 137.97m,
                            Total = 137.97m
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 6,
                            ComandaId = 1,
                            DataCreacio = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 10m,
                            Descripcio = "Impressora làser monocrom amb connexió Wi-Fi",
                            ImportDescompte = 9.00m,
                            NomProducte = "Impressora làser",
                            Ordre = 2,
                            PreuUnitari = 89.99m,
                            Quantitat = 1m,
                            Subtotal = 89.99m,
                            Total = 80.99m
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 3,
                            ComandaId = 1,
                            DataCreacio = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 5m,
                            Descripcio = "Teclat mecànic retroil·luminat amb switches Cherry MX",
                            ImportDescompte = 12.00m,
                            NomProducte = "Teclat mecànic",
                            Ordre = 3,
                            PreuUnitari = 120.00m,
                            Quantitat = 2m,
                            Subtotal = 240.00m,
                            Total = 228.00m
                        },
                        new
                        {
                            Id = 5,
                            ArticleId = 4,
                            ComandaId = 2,
                            DataCreacio = new DateTime(2025, 2, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Monitor LED Full HD 1920x1080 amb connexió HDMI",
                            ImportDescompte = 0m,
                            NomProducte = "Monitor 24 polzades",
                            Ordre = 0,
                            PreuUnitari = 189.99m,
                            Quantitat = 4m,
                            Subtotal = 759.96m,
                            Total = 759.96m
                        },
                        new
                        {
                            Id = 6,
                            ArticleId = 7,
                            ComandaId = 2,
                            DataCreacio = new DateTime(2025, 2, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Disc dur extern USB 3.0 de 1TB per còpies de seguretat",
                            ImportDescompte = 0m,
                            NomProducte = "Disc dur extern 1TB",
                            Ordre = 1,
                            PreuUnitari = 59.99m,
                            Quantitat = 3m,
                            Subtotal = 179.97m,
                            Total = 179.97m
                        },
                        new
                        {
                            Id = 7,
                            ArticleId = 5,
                            ComandaId = 3,
                            DataCreacio = new DateTime(2025, 2, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Cadira ergonòmica amb suport lumbar ajustable",
                            ImportDescompte = 0m,
                            NomProducte = "Cadira d'oficina",
                            Ordre = 0,
                            PreuUnitari = 149.99m,
                            Quantitat = 4m,
                            Subtotal = 599.96m,
                            Total = 599.96m
                        },
                        new
                        {
                            Id = 8,
                            ArticleId = 8,
                            ComandaId = 3,
                            DataCreacio = new DateTime(2025, 2, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Taula d'oficina de fusta amb calaixos i organitzador",
                            ImportDescompte = 0m,
                            NomProducte = "Taula d'oficina",
                            Ordre = 1,
                            PreuUnitari = 299.99m,
                            Quantitat = 1m,
                            Subtotal = 299.99m,
                            Total = 299.99m
                        },
                        new
                        {
                            Id = 9,
                            ArticleId = 2,
                            ComandaId = 4,
                            DataCreacio = new DateTime(2025, 2, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Ratolí òptic sense fils amb sensor de precisió",
                            ImportDescompte = 0m,
                            NomProducte = "Ratolí sense fils",
                            Ordre = 0,
                            PreuUnitari = 25.50m,
                            Quantitat = 3m,
                            Subtotal = 76.50m,
                            Total = 76.50m
                        },
                        new
                        {
                            Id = 10,
                            ArticleId = 3,
                            ComandaId = 4,
                            DataCreacio = new DateTime(2025, 2, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Teclat mecànic retroil·luminat amb switches Cherry MX",
                            ImportDescompte = 0m,
                            NomProducte = "Teclat mecànic",
                            Ordre = 1,
                            PreuUnitari = 120.00m,
                            Quantitat = 3m,
                            Subtotal = 360.00m,
                            Total = 360.00m
                        },
                        new
                        {
                            Id = 11,
                            ArticleId = 9,
                            ComandaId = 4,
                            DataCreacio = new DateTime(2025, 2, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 5m,
                            Descripcio = "Auriculars inalàmbrics amb cancel·lació de soroll",
                            ImportDescompte = 12.00m,
                            NomProducte = "Auriculars Bluetooth",
                            Ordre = 2,
                            PreuUnitari = 79.99m,
                            Quantitat = 3m,
                            Subtotal = 239.97m,
                            Total = 227.97m
                        },
                        new
                        {
                            Id = 12,
                            ArticleId = 4,
                            ComandaId = 5,
                            DataCreacio = new DateTime(2025, 2, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Monitor LED Full HD 1920x1080 amb connexió HDMI",
                            ImportDescompte = 0m,
                            NomProducte = "Monitor 24 polzades",
                            Ordre = 0,
                            PreuUnitari = 189.99m,
                            Quantitat = 2m,
                            Subtotal = 379.98m,
                            Total = 379.98m
                        },
                        new
                        {
                            Id = 13,
                            ArticleId = 8,
                            ComandaId = 5,
                            DataCreacio = new DateTime(2025, 2, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Taula d'oficina de fusta amb calaixos i organitzador",
                            ImportDescompte = 0m,
                            NomProducte = "Taula d'oficina",
                            Ordre = 1,
                            PreuUnitari = 299.99m,
                            Quantitat = 2m,
                            Subtotal = 599.98m,
                            Total = 599.98m
                        },
                        new
                        {
                            Id = 14,
                            ArticleId = 7,
                            ComandaId = 5,
                            DataCreacio = new DateTime(2025, 2, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            DescomptePercentatge = 0m,
                            Descripcio = "Disc dur extern USB 3.0 de 1TB per còpies de seguretat",
                            ImportDescompte = 0m,
                            NomProducte = "Disc dur extern 1TB",
                            Ordre = 2,
                            PreuUnitari = 59.99m,
                            Quantitat = 2m,
                            Subtotal = 119.98m,
                            Total = 119.98m
                        });
                });

            modelBuilder.Entity("ComandesAPI.Models.Usuari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("User");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuaris_Username");

                    b.ToTable("Usuaris");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@comandesjdsr.com",
                            FullName = "Administrador del Sistema",
                            IsEnabled = true,
                            PasswordHash = "$2a$12$wKQgs3QYMJdHm791BDWZ7eJCndZsZAvQYcbBQ9UCEs.sFP6Hp1LOW",
                            Role = "Administrator",
                            Username = "administrador"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "usuari@comandesjdsr.com",
                            FullName = "Usuari Estàndard",
                            IsEnabled = true,
                            PasswordHash = "$2a$12$wKQgs3QYMJdHm791BDWZ7eJCndZsZAvQYcbBQ9UCEs.sFP6Hp1LOW",
                            Role = "User",
                            Username = "usuari"
                        });
                });

            modelBuilder.Entity("ComandesAPI.Models.Comanda", b =>
                {
                    b.HasOne("ComandesAPI.Models.Usuari", "Usuari")
                        .WithMany()
                        .HasForeignKey("UsuariId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuari");
                });

            modelBuilder.Entity("ComandesAPI.Models.LiniaComanda", b =>
                {
                    b.HasOne("ComandesAPI.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ComandesAPI.Models.Comanda", "Comanda")
                        .WithMany("Linies")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("ComandesAPI.Models.Comanda", b =>
                {
                    b.Navigation("Linies");
                });
#pragma warning restore 612, 618
        }
    }
}
