// <auto-generated />
using System;
using ComandesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComandesAPI.Migrations
{
    [DbContext(typeof(ComandesDbContext))]
    [Migration("20251018163131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ComandesAPI.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actiu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataCreacio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataModificacio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Estoc")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Preu")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_Articles_Categoria");

                    b.HasIndex("Nom")
                        .HasDatabaseName("IX_Articles_Nom");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Ordinador portàtil per oficina amb pantalla de 15.6 polzades",
                            Estoc = 10,
                            Nom = "Ordinador portàtil",
                            Preu = 899.99m
                        },
                        new
                        {
                            Id = 2,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Ratolí òptic sense fils amb sensor de precisió",
                            Estoc = 50,
                            Nom = "Ratolí sense fils",
                            Preu = 25.50m
                        },
                        new
                        {
                            Id = 3,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Teclat mecànic retroil·luminat amb switches Cherry MX",
                            Estoc = 25,
                            Nom = "Teclat mecànic",
                            Preu = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Monitor LED Full HD 1920x1080 amb connexió HDMI",
                            Estoc = 15,
                            Nom = "Monitor 24 polzades",
                            Preu = 189.99m
                        },
                        new
                        {
                            Id = 5,
                            Actiu = true,
                            Categoria = "Mobiliari",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Cadira ergonòmica amb suport lumbar ajustable",
                            Estoc = 8,
                            Nom = "Cadira d'oficina",
                            Preu = 149.99m
                        },
                        new
                        {
                            Id = 6,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Impressora làser monocrom amb connexió Wi-Fi",
                            Estoc = 12,
                            Nom = "Impressora làser",
                            Preu = 89.99m
                        },
                        new
                        {
                            Id = 7,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Disc dur extern USB 3.0 de 1TB per còpies de seguretat",
                            Estoc = 30,
                            Nom = "Disc dur extern 1TB",
                            Preu = 59.99m
                        },
                        new
                        {
                            Id = 8,
                            Actiu = true,
                            Categoria = "Mobiliari",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Taula d'oficina de fusta amb calaixos i organitzador",
                            Estoc = 5,
                            Nom = "Taula d'oficina",
                            Preu = 299.99m
                        },
                        new
                        {
                            Id = 9,
                            Actiu = true,
                            Categoria = "Àudio",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Auriculars inalàmbrics amb cancel·lació de soroll",
                            Estoc = 20,
                            Nom = "Auriculars Bluetooth",
                            Preu = 79.99m
                        },
                        new
                        {
                            Id = 10,
                            Actiu = true,
                            Categoria = "Informàtica",
                            DataCreacio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcio = "Càmera web Full HD 1080p amb micròfon integrat",
                            Estoc = 18,
                            Nom = "Webcam HD",
                            Preu = 45.99m
                        });
                });

            modelBuilder.Entity("ComandesAPI.Models.Usuari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("User");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuaris_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuaris_Username");

                    b.ToTable("Usuaris");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@comandesjdsr.com",
                            FullName = "Administrador del Sistema",
                            IsEnabled = true,
                            PasswordHash = "$2a$12$wKQgs3QYMJdHm791BDWZ7eJCndZsZAvQYcbBQ9UCEs.sFP6Hp1LOW",
                            Role = "Administrator",
                            Username = "administrador"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "usuari@comandesjdsr.com",
                            FullName = "Usuari Estàndard",
                            IsEnabled = true,
                            PasswordHash = "$2a$12$wKQgs3QYMJdHm791BDWZ7eJCndZsZAvQYcbBQ9UCEs.sFP6Hp1LOW",
                            Role = "User",
                            Username = "usuari"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
